name: mouse_brain
channels:
  - simpleitk
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.1.2
  - matplotlib=3.1.1
  - numpy=1.16.4
  - python=3.7.4
  - scikit-image=0.15.0
  - simpleitk=1.2.2

